# Generated by Django 4.2.4 on 2024-07-06 21:31

import appPainel.models
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appPainel', '0003_historicalmonitoramentosubetapa_etapa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eixo',
            options={'verbose_name': 'Objetivo', 'verbose_name_plural': 'Objetivo Estratégico'},
        ),
        migrations.AlterModelOptions(
            name='historicaleixo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Objetivo', 'verbose_name_plural': 'historical Objetivo Estratégico'},
        ),
        migrations.RemoveField(
            model_name='historicalmonitoramentosubetapa',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='monitoramentosubetapa',
            name='etapa',
        ),
        migrations.AlterField(
            model_name='eixo',
            name='eixo_estrategico',
            field=models.CharField(max_length=255, verbose_name='Nome do Objetivo'),
        ),
        migrations.AlterField(
            model_name='eixo',
            name='eixo_estrategico_cd',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código do Objetivo'),
        ),
        migrations.AlterField(
            model_name='fontesmeta',
            name='valor',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BRL', max_digits=12, validators=[appPainel.models.validar_moeda], verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='historicaleixo',
            name='eixo_estrategico',
            field=models.CharField(max_length=255, verbose_name='Nome do Objetivo'),
        ),
        migrations.AlterField(
            model_name='historicaleixo',
            name='eixo_estrategico_cd',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Código do Objetivo'),
        ),
        migrations.AlterField(
            model_name='historicalfontesmeta',
            name='valor',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BRL', max_digits=12, validators=[appPainel.models.validar_moeda], verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='historicalmonitoramentosubetapa',
            name='subetapa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appPainel.subetapa', verbose_name='Meta | Etapa | Subetapa'),
        ),
        migrations.AlterField(
            model_name='monitoramentosubetapa',
            name='subetapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPainel.subetapa', verbose_name='Meta | Etapa | Subetapa'),
        ),
    ]
